# Generated by Django 3.2.10 on 2022-01-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_dpawregion'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpawregion',
            name='feat_id',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dpawregion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
